name: spec
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v6
      with:
        luaVersion: "5.4.2"
    - uses: leafo/gh-actions-luarocks@v2
    - name: build
      run: |
        luarocks install busted
        luarocks make
    - name: test
      run: |
        busted -o utfTerminal
